name = "QXRun"
uuid = "04c26001-d4a1-49d2-b090-1d469cf06784"
authors = ["QuantEx team"]
version = "0.1.0"

[deps]
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
TestSetExtensions = "2.0"
YAML = "0.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
